export const NEW_APP_STATE = 'NEW_APP_STATE';
export const SET_CAMPAIGN_DATES = 'SET_CAMPAIGN_DATES';

export const SET_CAMPAIGN_LENGTH = 'SET_CAMPAIGN_LENGTH';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_EVENT_FREQUENCY = 'SET_EVENT_FREQUENCY';

export const SEND_INVITES = 'SEND_INVITES';
export const INVITES_SENT = 'INVITES_SENT';

export const GET_STEPS = 'GET_STEPS';
export const STEPS_RECEIVED = 'STEPS_RECEIVED';
export const STEPS_FAILED = 'STEPS_FAILED';

export const SET_INITIAL_CAMPAIGN_DETAILS = 'SET_INITIAL_CAMPAIGN_DETAILS';
export const INITIAL_CAMPAIGN_DATA_RECEIVED = 'INITIAL_CAMPAIGN_DATA_RECEIVED';

export const FETCH_CAMPAIGN_INFO = 'FETCH_CAMPAIGN_INFO';
export const CAMPAIGN_INFO_RECEIVED = 'CAMPAIGN_INFO_RECEIVED';

export const SEND_JOIN_CAMPAIGN_REQUEST = 'SEND_JOIN_CAMPAIGN_REQUEST';
export const PLAYER_JOINED_CAMPAIGN = 'PLAYER_JOINED_CAMPAIGN';

export const CREATE_PLAYER = 'CREATE_PLAYER';
export const PLAYER_CREATED = 'PLAYER_CREATED';

export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED';

export const LEAVE_CAMPAIGN = 'LEAVE_CAMPAIGN';
export const CAMPAIGN_LEFT = 'CAMPAIGN_LEFT';

export const FETCH_PLAYER = 'FETCH_PLAYER';
export const PLAYER_FETCHED = 'PLAYER_FETCHED';

export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const PLAYER_UPDATED = 'PLAYER_UPDATED';

export const START_CAMPAIGN = 'START_CAMPAIGN';
export const CAMPAIGN_STARTED = 'CAMPAIGN_STARTED';

export const DESTROY_CAMPAIGN = 'DESTROY_CAMPAIGN';
export const CAMPAIGN_DESTROYED = 'CAMPAIGN_DESTROYED';

export const IS_PEDOMETER_AVAILABLE = 'IS_PEDOMETER_AVAILABLE';

export const UPDATE_PLAYER_STEPS = 'UPDATE_PLAYER_STEPS';

export const GET_LAST_STEP_STATE = 'GET_LAST_STEP_STATE';
export const SET_STEP_STATE = 'SET_STEP_STATE';

export const ADD_BONUS_STEPS = 'ADD_BONUS_STEPS';
export const ADD_SCAVENGED_ITEMS = 'ADD_SCAVENGED_ITEMS';
export const START_SCAVENGE = 'START_SCAVENGE';
export const GO_TO_SAFEHOUSE = 'GO_TO_SAFEHOUSE';
