export const NEW_APP_STATE = 'NEW_APP_STATE';
export const SET_CAMPAIGN_DATES = 'SET_CAMPAIGN_DATES';
export const GET_STEPS = 'GET_STEPS';
export const STEPS_RECEIVED = 'STEPS_RECEIVED';
export const STEPS_FAILED = 'STEPS_FAILED';
export const SET_CAMPAIGN_LENGTH = 'SET_CAMPAIGN_LENGTH';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_EVENT_FREQUENCY = 'SET_EVENT_FREQUENCY';
